# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=30, verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.CharField(blank=True, max_length=64, verbose_name='スペック'),
        ),
    ]
